version: "3.7"
services:
  ngpio:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    devices:
      - "/dev/gpiochip0"
      - "/dev/gpiochip1"
      - "/dev/gpiomem"
    container_name: node
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOINIT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOINITPASS}
  mongo-express:
    image: mongo-express 
    restart: always
    ports: 
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOINIT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOINITPASS}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGOINIT}:${MONGOINITPASS}@mongo:27017/"

    # working_dir: /usr/node
    # volumes:
    #   # - drupal_test4_dbdata:/var/lib/mysql
    #   - ./src:/usr/node/src